services:
  project-chaos:
    image: postgres:15
    container_name: project-chaos
    environment:
      POSTGRES_DB: project-chaos
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    restart: always